In [2]:
import numpy as np

# Generate random 16x16 matrices with integers between 0 and 9
np.random.seed(42)  # Set seed for reproducibility
A = np.random.randint(0, 10, (16, 16))
B = np.random.randint(0, 10, (16, 16))


# T1 of r=1
A = np.array(
    [[14,  7 ,12 , 7 ,15 ,15 ,10 ,12],
    [ 6, 14 ,13 , 5 , 4 , 2 ,18 ,12],
    [10,  3 , 8 , 4 ,12 , 6 , 8 , 3],
    [ 8,  8 , 6 , 9 , 8 , 7 ,10 , 9],
    [ 6,  9 ,11 ,12 , 8 ,11 ,10 , 6],
    [13, 14 , 8 , 7 , 7 ,15 ,10 , 1],
    [ 9,  6 ,12 ,11 , 7 , 8 ,14 , 8],
    [ 5,  2 , 4 , 8 ,15 ,14 ,14 ,10]],
)

# S1 of r = 1
B = np.array(
    [[14,  7, 12 , 7 ,15, 15, 10, 12,],
    [ 6 , 14, 13 , 5 , 4,  2, 18, 12,],
    [10 ,  3,  8 , 4 ,12,  6,  8,  3,],
    [ 8 ,  8,  6 , 9 , 8,  7, 10,  9,],
    [ 6 ,  9, 11 ,12 , 8, 11, 10,  6,],
    [13 , 14,  8 , 7 , 7, 15, 10,  1,],
    [15 , 12,  9 ,14 , 1,  8, 14,  7,],
    [ 5 ,  2,  4 , 8 ,15, 14, 14, 10,],]
)



print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)


Matrix A:
[[14  7 12  7 15 15 10 12]
 [ 6 14 13  5  4  2 18 12]
 [10  3  8  4 12  6  8  3]
 [ 8  8  6  9  8  7 10  9]
 [ 6  9 11 12  8 11 10  6]
 [13 14  8  7  7 15 10  1]
 [ 9  6 12 11  7  8 14  8]
 [ 5  2  4  8 15 14 14 10]]

Matrix B:
[[14  7 12  7 15 15 10 12]
 [ 6 14 13  5  4  2 18 12]
 [10  3  8  4 12  6  8  3]
 [ 8  8  6  9  8  7 10  9]
 [ 6  9 11 12  8 11 10  6]
 [13 14  8  7  7 15 10  1]
 [15 12  9 14  1  8 14  7]
 [ 5  2  4  8 15 14 14 10]]


In [3]:
def split_matrix(A):
    """Splits a square matrix A into four equal quadrants."""
    n = A.shape[0] // 2
    return A[:n, :n], A[:n, n:], A[n:, :n], A[n:, n:]

# Split matrices into quadrants
A11, A12, A21, A22 = split_matrix(A)
B11, B12, B21, B22 = split_matrix(B)

# Print quadrants
print("Quadrants of A:")
print("A11:\n", A11, "\nA12:\n", A12, "\nA21:\n", A21, "\nA22:\n", A22)

print("\nQuadrants of B:")
print("B11:\n", B11, "\nB12:\n", B12, "\nB21:\n", B21, "\nB22:\n", B22)


Quadrants of A:
A11:
 [[14  7 12  7]
 [ 6 14 13  5]
 [10  3  8  4]
 [ 8  8  6  9]] 
A12:
 [[15 15 10 12]
 [ 4  2 18 12]
 [12  6  8  3]
 [ 8  7 10  9]] 
A21:
 [[ 6  9 11 12]
 [13 14  8  7]
 [ 9  6 12 11]
 [ 5  2  4  8]] 
A22:
 [[ 8 11 10  6]
 [ 7 15 10  1]
 [ 7  8 14  8]
 [15 14 14 10]]

Quadrants of B:
B11:
 [[14  7 12  7]
 [ 6 14 13  5]
 [10  3  8  4]
 [ 8  8  6  9]] 
B12:
 [[15 15 10 12]
 [ 4  2 18 12]
 [12  6  8  3]
 [ 8  7 10  9]] 
B21:
 [[ 6  9 11 12]
 [13 14  8  7]
 [15 12  9 14]
 [ 5  2  4  8]] 
B22:
 [[ 8 11 10  6]
 [ 7 15 10  1]
 [ 1  8 14  7]
 [15 14 14 10]]


In [4]:
# Compute T matrices
T1 = A11 + A22
T2 = A21 + A22
T3 = A11
T4 = A22
T5 = A11 + A12
T6 = A21 - A11
T7 = A12 - A22

# Compute S matrices
S1 = B11 + B22
S2 = B11
S3 = B12 - B22
S4 = B21 - B11
S5 = B22
S6 = B11 + B12
S7 = B21 + B22

# Print T matrices
print("T Matrices:")
for i, T in enumerate([T1, T2, T3, T4, T5, T6, T7], 1):
    print(f"T{i}:\n{T}\n")

# Print S matrices
print("S Matrices:")
for i, S in enumerate([S1, S2, S3, S4, S5, S6, S7], 1):
    print(f"S{i}:\n{S}\n")


T Matrices:
T1:
[[22 18 22 13]
 [13 29 23  6]
 [17 11 22 12]
 [23 22 20 19]]

T2:
[[14 20 21 18]
 [20 29 18  8]
 [16 14 26 19]
 [20 16 18 18]]

T3:
[[14  7 12  7]
 [ 6 14 13  5]
 [10  3  8  4]
 [ 8  8  6  9]]

T4:
[[ 8 11 10  6]
 [ 7 15 10  1]
 [ 7  8 14  8]
 [15 14 14 10]]

T5:
[[29 22 22 19]
 [10 16 31 17]
 [22  9 16  7]
 [16 15 16 18]]

T6:
[[-8  2 -1  5]
 [ 7  0 -5  2]
 [-1  3  4  7]
 [-3 -6 -2 -1]]

T7:
[[  7   4   0   6]
 [ -3 -13   8  11]
 [  5  -2  -6  -5]
 [ -7  -7  -4  -1]]

S Matrices:
S1:
[[22 18 22 13]
 [13 29 23  6]
 [11 11 22 11]
 [23 22 20 19]]

S2:
[[14  7 12  7]
 [ 6 14 13  5]
 [10  3  8  4]
 [ 8  8  6  9]]

S3:
[[  7   4   0   6]
 [ -3 -13   8  11]
 [ 11  -2  -6  -4]
 [ -7  -7  -4  -1]]

S4:
[[-8  2 -1  5]
 [ 7  0 -5  2]
 [ 5  9  1 10]
 [-3 -6 -2 -1]]

S5:
[[ 8 11 10  6]
 [ 7 15 10  1]
 [ 1  8 14  7]
 [15 14 14 10]]

S6:
[[29 22 22 19]
 [10 16 31 17]
 [22  9 16  7]
 [16 15 16 18]]

S7:
[[14 20 21 18]
 [20 29 18  8]
 [16 20 23 21]
 [20 16 18 18]]



In [5]:
# Compute Q matrices
Q1 = T1 @ S1
Q2 = T2 @ S2
Q3 = T3 @ S3
Q4 = T4 @ S4
Q5 = T5 @ S5
Q6 = T6 @ S6
Q7 = T7 @ S7

# Print Q matrices
print("Q Matrices:")
for i, Q in enumerate([Q1, Q2, Q3, Q4, Q5, Q6, Q7], 1):
    print(f"Q{i}:\n{Q}\n")


Q Matrices:
Q1:
[[1259 1446 1642  883]
 [1054 1460 1579  710]
 [1035 1131 1351  757]
 [1449 1690 1832 1012]]

Q2:
[[670 585 704 444]
 [698 664 809 429]
 [720 538 696 457]
 [700 562 700 454]]

Q3:
[[ 160 -108  -44  106]
 [ 108 -219   14  133]
 [ 121  -43  -40   57]
 [  35 -147   -8  103]]

Q4:
[[ 45  70 -65 156]
 [ 96  98 -74 164]
 [ 46  92 -49 183]
 [ 18  96 -91 233]]

Q5:
[[ 693 1091 1084  540]
 [ 478  836  932  463]
 [ 360  603  632  323]
 [ 519  781  786  403]]

Q6:
[[-154  -78  -50  -35]
 [ 125  139  106  134]
 [ 201  167  247  186]
 [-207 -195 -300 -191]]

Q7:
[[ 298  352  327  266]
 [  46 -101   85  208]
 [-166 -158 -159 -142]
 [-322 -439 -383 -284]]



In [6]:
# Compute C submatrices
C11 = Q1 + Q4 - Q5 + Q7
C12 = Q3 + Q5
C21 = Q2 + Q4
C22 = Q1 - Q2 + Q3 + Q6

# Reconstruct full C matrix
C_top = np.hstack((C11, C12))
C_bottom = np.hstack((C21, C22))
C = np.vstack((C_top, C_bottom))

print("Final Matrix C = A * B:")
print(C)


Final Matrix C = A * B:
[[ 909  777  820  765  853  983 1040  646]
 [ 718  621  658  619  586  617  946  596]
 [ 555  462  511  475  481  560  592  380]
 [ 626  566  572  558  554  634  778  506]
 [ 715  655  639  600  595  675  844  510]
 [ 794  762  735  593  589  716  890  548]
 [ 766  630  647  640  637  717  862  543]
 [ 718  658  609  687  577  786  824  470]]


In [8]:

# Define input tensor (C_in=3, H=3, W=4)
input_tensor = np.random.rand(3, 5, 4)  # 3 channels, 3x4 image

# Define kernel (C_in=3, H=2, W=2, C_out=1)
kernel = np.random.rand(1, 3, 2, 2)  # 1 output channel, 3 input channels

# Traditional convolution
output_height = input_tensor.shape[1] - kernel.shape[2] + 1
output_width = input_tensor.shape[2] - kernel.shape[3] + 1
output_traditional = np.zeros((1, output_height, output_width))

for oc in range(1):  # Output channels
    for h in range(output_height):
        for w in range(output_width):
            output_traditional[oc, h, w] = np.sum(
                input_tensor[:, h:h+2, w:w+2] * kernel[oc]
            )

# Convolution using GEMM

# Step 1: Unfold input into a matrix
patches = []
for h in range(output_height):
    for w in range(output_width):
        patches.append(input_tensor[:, h:h+2, w:w+2].reshape(-1))
input_matrix = np.array(patches)  # Shape: (output_height * output_width, C_in * kernel_h * kernel_w)

# Step 2: Reshape kernel
kernel_matrix = kernel.reshape(1, -1)  # Shape: (C_out, C_in * kernel_h * kernel_w)

# Step 3: Compute GEMM-based convolution
output_gemm = (input_matrix @ kernel_matrix.T).T.reshape(1, output_height, output_width)

# Compare results
print("Traditional Convolution Result:")
print(output_traditional)
print("\nGEMM-based Convolution Result:")
print(output_gemm)
print("\nDifference:")
print(output_traditional - output_gemm)


Traditional Convolution Result:
[[[4.18973669 3.92337903 3.65210829]
  [3.57753733 4.49610329 5.05527133]
  [2.74169715 4.6376215  4.11684037]
  [2.76229605 3.74246662 2.73047119]]]

GEMM-based Convolution Result:
[[[4.18973669 3.92337903 3.65210829]
  [3.57753733 4.49610329 5.05527133]
  [2.74169715 4.6376215  4.11684037]
  [2.76229605 3.74246662 2.73047119]]]

Difference:
[[[ 0.0000000e+00  4.4408921e-16 -8.8817842e-16]
  [ 0.0000000e+00  0.0000000e+00  8.8817842e-16]
  [ 4.4408921e-16 -8.8817842e-16  0.0000000e+00]
  [-4.4408921e-16 -4.4408921e-16  0.0000000e+00]]]
